apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicec
  template:
    metadata:
      labels:
        app: servicec
    spec:
      containers:
      - name: servicec
        image: phil91ip/servicec:latest
        ports:
        - containerPort: 8082